name: Check H&M Stock

on:
  workflow_dispatch: # Das erlaubt manuelles Auslösen
  schedule:
    # Führe die Aktion jede Stunde aus
    - cron: cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager requests

    - name: Run script
      run: |
        python hmrestock.py
