name: Restock Bot

on:
  schedule:
    # Läuft alle 5 Minuten
    - cron: '*/5 * * * *'

jobs:
  restock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager requests

      - name: Run restock script
        run: python restock.py
